LINE_SEPARATORS = "-----------------------------------------------------------------------------------------------------------------------------"
WELCOME_STRING = "Welcome to the Droid Command line Interface.\n Type 'guide' for help-manual.\n Use 'leave' to exit."
ERROR_DEF_STRING = " do not exist.\n Type 'guide' for help-manual.\n Use 'leave' to exit"
PROMPT = ">> "
LEAVE = "leave"
GUIDE_PATH = "C:\\Users\\abc\\Desktop\\PythonProject\\guide.txt"
DEFAULT_START_PATH = "C:\\Users\\abc"